sonar.projectKey=raxj06
sonar.organization=raxj06
sonar.projectName=secureship
sonar.sources=services
sonar.exclusions=**/node_modules/**,**/dist/**,**/tests/**,**/*.test.ts,**/prisma/**,**/coverage/**
sonar.javascript.lcov.reportPaths=services/api-gateway/coverage/lcov.info,services/order-service/coverage/lcov.info,services/tracking-service/coverage/lcov.info,services/notification-service/coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.base.json
