replicas: 1
persistence:
  enabled: false
adminPassword: secureship-dev
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc:80
        isDefault: true
service:
  type: ClusterIP
