{{- range $name, $svc := .Values.services }}
{{- if $svc.secrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $name }}-secrets
  namespace: {{ $.Values.namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: {{ $name }}-secrets
    creationPolicy: Owner
  data:
{{- range $svc.secrets }}
    - secretKey: {{ .key }}
      remoteRef:
        key: {{ .remoteKey }}
        property: {{ .property }}
{{- end }}
{{- end }}
{{- end }}
